CREATE TRIGGER TRG_BFR_DELETE 
BEFORE DELETE ON OGRENCILER
BEGIN
INSERT INTO OGRENCILER_LOG 
(OGR_ID,OGR_TC,OGR_ADI,OGR_SOYADI,CINSIYET,ZAMAN,ISLEM)
VALUES 
(old.ID,old.OGR_TC,old.OGR_ADI,old.OGR_SOYADI,old.CINSIYET,datetime('now'),3);
END;

CREATE TRIGGER TRG_BFR_INS 
BEFORE INSERT ON OGRENCILER 
BEGIN 
INSERT INTO OGRENCILER_LOG 
(OGR_ID,OGR_TC,OGR_ADI,OGR_SOYADI,CINSIYET,ZAMAN,ISLEM)
 VALUES 
 (NEW.ID,NEW.OGR_TC,NEW.OGR_ADI,NEW.OGR_SOYADI,NEW.CINSIYET,datetime('NOW'),1); 
 END;

 
 CREATE TRIGGER TRG_BFR_UPDT 
 BEFORE UPDATE 
 ON OGRENCILER 
 BEGIN 
 INSERT INTO OGRENCILER_LOG 
 (OGR_ID,OGR_TC,OGR_ADI,OGR_SOYADI,CINSIYET,ZAMAN,ISLEM) 
 VALUES 
 (old.ID,old.OGR_TC,old.OGR_ADI,old.OGR_SOYADI,old.CINSIYET,
 datetime('now'),2); 
 END;